### PR TITLE
cosmetic changes, UX fix

### PR DESCRIPTION
**Pull request by codynguyen1116**
- replacing old brickimedia svg with new svg
- merging longer CSS properties into one shorthand property
- using responsive ems for font properties instead of px units
- lowercasing color hex codes
- removing some unnecessary vendor prefixes 
- fix placeholder search issue (however we still need to come up with something for IE9)

### CODE REVIEW

**Comment by codynguyen1116** [comment]
Something to add at the end, I've had technical difficulties trying to replace the old brickimedia meta png file through Github Desktop and it'd keep saying either validaiton failed if I create a pull request or "you don't have direct commit access to this repository"  when I press sync (which is true, I don't), so would someone else be able to replace it? 

Also, this pull request relates to issue #434

**Comment by MtMNC** [comment]
All looks good to me. I'm so excellent at messing up pull requests that I'd rather have another person check it over before merging though. :P

And you should TOTALLY have commit access! I can't give it to you unfortunately, but @georgebarnick could you?

**Comment by seaside98** [comment]
Looks good to me.

**Comment by codynguyen1116** [comment]
@MtMNC Haha thanks I actually agree with the code review thing but it'd be pretty nice to have commit access, it makes it faster to help out development here. :D :P

**Comment by MtMNC** [comment]
@codynguyen1116 TBH I thought you had it already and you were using pull requests so people could provide feedback. :P

**Pull request merged**
